"""Cross-reference Virginia emergency declarations with NCEI Storm Events.

For each declaration, this script finds Virginia events whose begin date falls
within a configurable window around the signing date.  NCEI can report an event
against a county/county-equivalent (CZ_TYPE=C), an NWS public forecast zone
(CZ_TYPE=Z), or a marine zone (CZ_TYPE=M).  The output preserves that distinction
so a forecast zone is not silently presented as a legal locality.

Hazard filtering: a declaration's description is scanned for recognized hazard
keywords (drought, wildfire, flood, hurricane, winter, tornado, wind, plus a
broader storm/storm-related/nor'easter/weather-conditions catch-all, used only
as a fallback when nothing more specific matched) to decide which NCEI
EVENT_TYPE values are plausible matches. "Water emergency" is deliberately
NOT auto-classified - see compatible_event_types()'s docstring and the
"water" category's own comment in HAZARD_EVENT_TYPES for why a keyword alone
cannot safely tell a drought-driven water emergency apart from a
hurricane-driven one. When a description matches NONE of the recognized
keywords - a generic title like "Declaration of a State of Emergency" with
no hazard-specific language - the match is AMBIGUOUS. By default an
ambiguous declaration is skipped (no NCEI search is attempted for it) rather
than silently matching every recorded event type in the window, which
previously produced large, unrelated result sets for generically-titled
declarations. Pass --unmatched-hazard-policy all to opt into that old
behavior explicitly for an entire run; every declaration this affects is
printed as a warning either way, and summarized again at the end of the run.

A single declaration can also carry its own reviewed answer via an optional
hazard_category_override column, instead of waiting on a run-wide flag - see
resolve_override() for the exact format. This is the mechanism for clearing
one generically-titled declaration at a time (e.g. after reading its source
document) without changing behavior for the rest of the state's declarations.

The recommended way to apply reviewed overrides is a durable sidecar file
(--overrides plus/<state>/hazard_overrides.csv), NOT editing
declarations_for_join.csv directly - that file is regenerated by each
collection run and would silently lose any override written into it. See
load_overrides() and apply_overrides() for the sidecar schema, including the
reserved "exclude" value for dropping non-weather records (administrative,
procurement, memorial, policy orders, etc.) from the join entirely.

Required input columns:
  eo_number,event_description,date_signed

Historical inventories may also supply declaration_id, governor,
archive_record_url, and hazard_category_override.  Those fields are retained
in both outputs (except hazard_category_override, which is consumed here and
not carried into the match/severity CSVs).  A stable declaration_id is
important because EO numbers repeat across administrations.

Usage:
  python eo_storm_join.py --declarations declarations_for_join.csv --out matches.csv
"""

import argparse
import gzip
import io
import re
import sys
from datetime import timedelta

import pandas as pd
import requests


INDEX_URL = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/"
FILE_PATTERN = re.compile(
    r"StormEvents_details-ftp_v1\.0_d(\d{4})_c(\d{8})\.csv\.gz"
)
DEFAULT_WINDOW_DAYS = 3
UNMATCHED_HAZARD_POLICIES = ("skip", "all")
DEFAULT_UNMATCHED_HAZARD_POLICY = "skip"

# A reserved hazard_category_override value (case-insensitive) meaning "this
# declaration does not belong in the weather join at all" - for records a
# reviewer has identified as non-event contamination (administrative,
# procurement, memorial, policy orders, etc.). Distinct from an ambiguous/
# skipped declaration: an excluded declaration is a resolved decision, not
# an unresolved one, and is never reported alongside the ambiguous list.
EXCLUDE_SENTINEL = "exclude"

REQUIRED_OVERRIDE_COLUMNS = {"declaration_id", "hazard_category_override"}
OPTIONAL_OVERRIDE_COLUMNS = ["review_note", "source_url"]

AREA_TYPE_LABELS = {
    "C": "county/county-equivalent",
    "Z": "NWS forecast zone",
    "M": "marine zone",
}

DECLARATION_COLUMNS = [
    "declaration_id",
    "eo_number",
    "governor",
    "event_description",
    "date_signed",
    "archive_record_url",
]

EVENT_COLUMNS = [
    "EVENT_ID",
    "EPISODE_ID",
    "BEGIN_DATE_TIME",
    "END_DATE_TIME",
    "CZ_TYPE",
    "area_type",
    "CZ_FIPS",
    "CZ_NAME",
    "EVENT_TYPE",
    "MAGNITUDE",
    "MAGNITUDE_TYPE",
    "DEATHS_DIRECT",
    "INJURIES_DIRECT",
    "DAMAGE_PROPERTY",
    "DAMAGE_CROPS",
    "SOURCE",
    "EPISODE_NARRATIVE",
    "EVENT_NARRATIVE",
]

HAZARD_EVENT_TYPES = {
    "drought": {"Drought"},
    "fire": {"Wildfire", "Drought", "High Wind", "Strong Wind"},
    "flood": {
        "Flash Flood",
        "Flood",
        "Coastal Flood",
        "Lakeshore Flood",
        "Heavy Rain",
        "Debris Flow",
        "Landslide",
    },
    "severe_storm": {
        "Tornado",
        "Thunderstorm Wind",
        "Hail",
        "Lightning",
        "Heavy Rain",
        "Flash Flood",
    },
    "tropical": {
        "Hurricane (Typhoon)",
        "Tropical Storm",
        "Storm Surge/Tide",
        "Coastal Flood",
        "High Wind",
        "Strong Wind",
        "Flash Flood",
        "Flood",
        "Heavy Rain",
        "Tornado",
        "Thunderstorm Wind",
    },
    "wind": {"High Wind", "Strong Wind", "Thunderstorm Wind"},
    # A title that only says "storm," "storm-related," "nor'easter," or
    # "weather conditions/related" is real weather but doesn't say which kind.
    # This is deliberately broader than the single-hazard categories above -
    # it is still far narrower than "every NCEI event type," which was the
    # original bug - and exists specifically because the 2026-09-05 cross-
    # state validation found generically-worded titles for real weather
    # events being skipped entirely under the fail-closed default.
    "storm_general": {
        "Thunderstorm Wind",
        "Hail",
        "High Wind",
        "Strong Wind",
        "Flash Flood",
        "Flood",
        "Heavy Rain",
        "Winter Storm",
        "Winter Weather",
        "Coastal Flood",
        "Tornado",
        "Blizzard",
        "Ice Storm",
    },
    # "Water emergency" is deliberately NOT auto-classified. The 2026-09-05
    # validation found two NJ cases with that exact phrase that need
    # different NCEI event types (McGreevey EO-11 reads as drought/water-
    # supply; Christie EO-106 was Hurricane Sandy and needs tropical types) -
    # a keyword alone cannot tell those apart safely, so a description that
    # only says "water emergency" stays ambiguous and must be resolved via
    # hazard_category_override once a reviewer has read the source document.
    # "water" remains available below as a category name for that override,
    # for the genuinely drought/water-supply cases.
    "water": {"Flood", "Flash Flood", "Heavy Rain", "Drought"},
    "winter": {
        "Winter Storm",
        "Winter Weather",
        "Ice Storm",
        "Heavy Snow",
        "Blizzard",
        "Sleet",
        "Cold/Wind Chill",
        "Extreme Cold/Wind Chill",
        "Frost/Freeze",
        "High Wind",
        "Strong Wind",
    },
}

_year_cache = {}


def get_latest_filenames_by_year():
    """Return the most recently certified details filename for each year."""
    response = requests.get(INDEX_URL, timeout=30)
    response.raise_for_status()
    latest = {}
    for match in FILE_PATTERN.finditer(response.text):
        year, certification_date = match.group(1), match.group(2)
        filename = match.group(0)
        if year not in latest or certification_date > latest[year][1]:
            latest[year] = (filename, certification_date)
    return {year: filename for year, (filename, _) in latest.items()}


def download_year_details(filename):
    response = requests.get(INDEX_URL + filename, timeout=60)
    response.raise_for_status()
    with gzip.GzipFile(fileobj=io.BytesIO(response.content)) as archive:
        frame = pd.read_csv(archive, low_memory=False)
    # NCEI stores values such as "24-JAN-26 21:00:00".
    frame["BEGIN_DATE_TIME"] = pd.to_datetime(
        frame["BEGIN_DATE_TIME"], format="%d-%b-%y %H:%M:%S", errors="coerce"
    )
    frame["END_DATE_TIME"] = pd.to_datetime(
        frame["END_DATE_TIME"], format="%d-%b-%y %H:%M:%S", errors="coerce"
    )
    return frame


def get_year_events(year, filenames, state):
    year_text = str(year)
    cache_key = (year_text, state.upper())
    if cache_key in _year_cache:
        return _year_cache[cache_key]
    if year_text not in filenames:
        print(f"No NCEI file published yet for {year_text}.", file=sys.stderr)
        _year_cache[cache_key] = pd.DataFrame()
        return _year_cache[cache_key]
    frame = download_year_details(filenames[year_text])
    # Historical runs span more than two decades.  Retaining only the selected
    # state's records keeps the cache small while still downloading each year once.
    frame = frame[frame["STATE"].fillna("").str.upper() == state.upper()].copy()
    _year_cache[cache_key] = frame
    return _year_cache[cache_key]


def compatible_event_types(description):
    """Infer plausible NCEI event types from an executive-order title.

    Returns an EMPTY set when no recognized hazard keyword is present. Callers
    must not treat an empty set as "no restriction" - see
    resolve_allowed_types(), which is the only place that decision is made.

    storm_general is a deliberately broad fallback for a description that
    ONLY says "storm"/"storm-related"/"nor'easter"/"weather conditions" with
    no more specific hazard word. It must never be unioned alongside an
    already-specific category (winter, tropical, flood, severe_storm, wind,
    fire, drought) - doing so silently reintroduces the same "match nearly
    everything" failure mode this module was built to eliminate, just via a
    different path. A description like "winter storm" contains the bare word
    "storm" as well as "winter"; without this guard, the specific "winter"
    match gets diluted by storm_general's own Flood/Tornado/Thunderstorm
    Wind/Hail/etc., letting a purely winter declaration match an NCEI flood
    or tornado record. Confirmed in production: PA's "A complex winter storm
    system... heavy snow and strong winds" matched a Flood record in
    Armstrong County for exactly this reason (2026-09-05 five-state
    retest). storm_general is therefore only appended when nothing more
    specific already matched.
    """
    text = str(description).lower()
    categories = []
    if "drought" in text:
        categories.append("drought")
    if re.search(r"\b(?:wildfire|forest fire|brush fire)s?\b", text):
        categories.append("fire")
    if re.search(r"\b(?:flood|flooding|rainfall|heavy rain|mudslide|landslide)", text):
        categories.append("flood")
    if re.search(r"\b(?:hurricane|tropical storm|tropical depression|tropical weather)", text):
        categories.append("tropical")
    if re.search(r"\b(?:winter|snow|ice|icing|sleet|blizzard|cold|freeze|freezing)", text):
        categories.append("winter")
    if re.search(r"\b(?:tornado|severe storm|severe weather|thunderstorm|hail|lightning)", text):
        categories.append("severe_storm")
    if re.search(r"\b(?:wind|winds|wind damage)", text):
        categories.append("wind")
    if not categories:
        generic_storm = re.search(
            r"\bstorms?\b|storm[- ]related|nor['\u2019]?\s?easter|noreaster", text
        )
        generic_weather = re.search(r"\bweather[- ]related\b|\bweather conditions?\b", text)
        if generic_storm or generic_weather:
            categories.append("storm_general")
    allowed = set()
    for category in categories:
        allowed.update(HAZARD_EVENT_TYPES[category])
    return allowed


def resolve_override(override_value):
    """Parse an optional, human-reviewed hazard_category_override cell.

    A reviewer who has looked at the source document for a generically-titled
    declaration (a bare "State of Emergency" with no recoverable weather
    keyword) can write the real answer directly into the declarations CSV
    instead of relying on a keyword guess. The value is a comma-separated
    list of either HAZARD_EVENT_TYPES category names (e.g. "flood,tropical")
    or literal NCEI EVENT_TYPE strings drawn from those same categories
    (e.g. "Coastal Flood"), or any mix of the two.

    This exists specifically because --unmatched-hazard-policy applies to an
    entire run, not to one declaration - the 2026-09-05 cross-state
    validation flagged that as a real gap: reviewing NY/NC/NJ's generic
    declarations one at a time needs a per-row mechanism, not a global flag
    that would reintroduce the original over-match risk everywhere else in
    the same run.

    Returns None if override_value is genuinely blank/missing/NaN (no
    override present for this declaration - the normal case). pandas reads
    an empty CSV cell as float NaN, not an empty string, so that check must
    happen before any str()/strip() conversion; treating a stray "nan" as a
    literal token was a real bug in an earlier version of this function.

    Raises ValueError if override_value is non-blank but resolves to zero
    usable tokens (e.g. ", ,") or contains any token that is neither a known
    HAZARD_EVENT_TYPES category name nor a literal EVENT_TYPE value found in
    one of those categories. Both are treated as hard errors, not silently
    downgraded to "no restriction" - an unrecognized or empty override must
    never be allowed to fall through to the "no restriction" meaning that an
    empty set carries elsewhere in this module, since that was exactly the
    original inflation bug.
    """
    if override_value is None or pd.isna(override_value):
        return None

    text = str(override_value).strip()
    if not text:
        return None

    tokens = [token.strip() for token in text.split(",") if token.strip()]
    if not tokens:
        raise ValueError(
            "hazard_category_override contains no usable categories or event types"
        )

    known_event_types = set().union(*HAZARD_EVENT_TYPES.values())
    allowed = set()

    for token in tokens:
        if token in HAZARD_EVENT_TYPES:
            allowed.update(HAZARD_EVENT_TYPES[token])
        elif token in known_event_types:
            allowed.add(token)
        else:
            raise ValueError(
                f"Unknown hazard_category_override value: {token!r}"
            )

    return allowed


def load_overrides(path):
    """Load a durable sidecar hazard-override file.

    Sidecar files are the durable, human-reviewed source of truth for
    declarations a keyword search cannot safely classify. They live outside
    declarations_for_join.csv on purpose: that file is regenerated by each
    collection run and would silently erase any override written directly
    into it. Recommended location: plus/<state>/hazard_overrides.csv.

    Required columns: declaration_id, hazard_category_override.
    Optional columns: review_note, source_url - audit trail only, never
    used for matching logic.

    hazard_category_override accepts everything resolve_override() accepts
    (comma-separated HAZARD_EVENT_TYPES category names and/or literal
    EVENT_TYPE values), plus one reserved value, EXCLUDE_SENTINEL
    ("exclude", case-insensitive), which drops a declaration from the join
    entirely - for records identified as not belonging in the weather input
    at all, which a fresh collection run would otherwise keep re-introducing
    if the fix were only made by deleting rows from the generated CSV.

    Every row is fully normalized and validated here, at load time, before
    anything is merged against the actual declarations or any NCEI request
    is made:
      - declaration_id is trimmed; a blank/NaN/whitespace-only id raises.
      - review_note/source_url are trimmed (blank is fine - they're audit
        text only).
      - hazard_category_override is required to be non-blank for every row.
      - every non-"exclude" hazard_category_override value is validated by
        calling resolve_override() on it - for EVERY row, including rows
        whose declaration_id turns out not to match anything in the current
        declarations CSV. Skipping validation for those would mean a typo
        in an already-stale row (one that will only ever produce an
        unmatched-id warning downstream) could sit in a sidecar file
        indefinitely without ever being caught, which contradicts this
        file's whole point of failing loudly on malformed input.
      - duplicate detection runs AFTER declaration_id is trimmed, so
        "A-1 " and "A-1" are correctly treated as the same id.

    Raises ValueError on any of the above. A malformed sidecar must halt
    the run before any matching starts, not surface later as a silent
    unmatched-id warning or a quietly-wrong match.
    """
    overrides = pd.read_csv(path, dtype=str)
    missing = sorted(REQUIRED_OVERRIDE_COLUMNS.difference(overrides.columns))
    if missing:
        raise ValueError(f"Overrides file {path} is missing: " + ", ".join(missing))
    for column in OPTIONAL_OVERRIDE_COLUMNS:
        if column not in overrides.columns:
            overrides[column] = ""

    overrides["declaration_id"] = (
        overrides["declaration_id"].fillna("").astype(str).str.strip()
    )
    if (overrides["declaration_id"] == "").any():
        raise ValueError(f"Overrides file {path} contains a blank declaration_id")

    for column in OPTIONAL_OVERRIDE_COLUMNS:
        overrides[column] = overrides[column].fillna("").astype(str).str.strip()

    duplicate_ids = sorted(
        overrides.loc[overrides["declaration_id"].duplicated(), "declaration_id"].unique()
    )
    if duplicate_ids:
        raise ValueError(
            f"Overrides file {path} has duplicate declaration_id values: "
            + ", ".join(duplicate_ids)
        )

    for _, row in overrides.iterrows():
        value = row["hazard_category_override"]
        if pd.isna(value) or not str(value).strip():
            raise ValueError(
                f"Overrides file {path}, declaration_id {row['declaration_id']!r}: "
                "blank hazard_category_override"
            )
        if str(value).strip().lower() != EXCLUDE_SENTINEL:
            # Validate now, regardless of whether this id matches anything
            # in the current declarations CSV - see docstring above.
            resolve_override(value)

    return overrides


def apply_overrides(declarations, overrides):
    """Merge a sidecar overrides file into declarations by declaration_id.

    A sidecar entry always wins over anything already in the declarations
    CSV's own hazard_category_override column (if it even has one) - the
    sidecar is the durable, reviewed source of truth, and the generated CSV
    is not. Any declaration_id in the sidecar with no matching row in
    declarations is reported as a warning, not silently ignored: it usually
    means an upstream id changed, or that declaration was dropped by a newer
    collection run, and a reviewed override that no longer applies to
    anything should stay visible rather than quietly doing nothing.
    """
    declarations = declarations.copy()
    declarations["declaration_id"] = declarations["declaration_id"].astype(str)
    if "hazard_category_override" not in declarations.columns:
        declarations["hazard_category_override"] = ""
    declarations["override_review_note"] = ""
    declarations["override_source_url"] = ""

    known_ids = set(declarations["declaration_id"])
    unmatched = []
    for _, row in overrides.iterrows():
        declaration_id = row["declaration_id"]
        if declaration_id not in known_ids:
            unmatched.append(declaration_id)
            continue
        mask = declarations["declaration_id"] == declaration_id
        declarations.loc[mask, "hazard_category_override"] = row["hazard_category_override"]
        declarations.loc[mask, "override_review_note"] = row["review_note"]
        declarations.loc[mask, "override_source_url"] = row["source_url"]

    if unmatched:
        print(
            f"WARNING: {len(unmatched)} override(s) in the sidecar file did not "
            "match any declaration_id in the current declarations CSV (the "
            "declaration may have been removed or renumbered by a newer "
            "collection run): " + ", ".join(unmatched),
            file=sys.stderr,
        )
    return declarations


def resolve_allowed_types(
    description, hazard_filter, unmatched_hazard_policy, override=None
):
    """Decide which NCEI EVENT_TYPE values a declaration's storm search should
    be restricted to, and flag when its description didn't match any known
    hazard keyword.

    Returns (allowed_types, ambiguous):
      - override is present (see resolve_override): allowed_types is the
        reviewer-supplied set, ambiguous=False. A human already resolved
        this declaration, so it is never flagged as ambiguous and always
        wins over both the keyword guess and hazard_filter/--no-hazard-filter.
      - hazard_filter is False (--no-hazard-filter): allowed_types=set()
        (no restriction, search every event type), ambiguous=False. This is
        an explicit, deliberate user choice, so nothing is flagged.
      - description matched at least one hazard keyword: allowed_types is
        that keyword-derived set, ambiguous=False.
      - description matched NO hazard keyword: ambiguous=True, and
        allowed_types depends on unmatched_hazard_policy:
          "skip" (default): allowed_types=None, meaning "match nothing".
            An unclassifiable description should not silently pull in every
            NCEI event recorded statewide in the window - that was the bug.
          "all": allowed_types=set() (no restriction), reproducing the old
            behavior, but only when explicitly requested, and always flagged
            by the caller as ambiguous so it shows up in the run's output.
    """
    resolved_override = resolve_override(override)
    if resolved_override is not None:
        return resolved_override, False
    if not hazard_filter:
        return set(), False
    categories = compatible_event_types(description)
    if categories:
        return categories, False
    if unmatched_hazard_policy == "all":
        return set(), True
    return None, True


def events_near_date(state, center_date, window_days, filenames, allowed_types):
    """Return NCEI events for a state within window_days of center_date.

    allowed_types (see resolve_allowed_types):
      - None: matches nothing. Used when hazard filtering is on, the
        description matched no recognized keyword, and the caller's
        unmatched-hazard policy is "skip" (the default).
      - falsy (empty set): no restriction; every recorded event type in the
        window is returned. Used for --no-hazard-filter and for the explicit
        --unmatched-hazard-policy all opt-in.
      - non-empty set: only events whose EVENT_TYPE is in this set.
    """
    if allowed_types is None:
        return pd.DataFrame(columns=EVENT_COLUMNS)

    start = center_date - timedelta(days=window_days)
    end = center_date + timedelta(days=window_days)
    frames = [
        get_year_events(year, filenames, state)
        for year in range(start.year, end.year + 1)
    ]
    frames = [frame for frame in frames if not frame.empty]
    if not frames:
        return pd.DataFrame()
    events = pd.concat(frames, ignore_index=True)
    mask = (
        (events["BEGIN_DATE_TIME"].dt.date >= start)
        & (events["BEGIN_DATE_TIME"].dt.date <= end)
    )
    matches = events.loc[mask]
    if allowed_types:
        matches = matches[matches["EVENT_TYPE"].isin(allowed_types)]
    return matches


def parse_damage(value):
    """Convert NCEI damage values such as 200K or 1.5M to dollars."""
    if pd.isna(value):
        return 0.0
    text = str(value).strip().upper()
    if not text:
        return 0.0
    multipliers = {"K": 1_000.0, "M": 1_000_000.0, "B": 1_000_000_000.0}
    multiplier = multipliers.get(text[-1], 1.0)
    if text[-1] in multipliers:
        text = text[:-1]
    try:
        return float(text) * multiplier
    except ValueError:
        return 0.0


def build_severity_summary(result):
    """Aggregate reported human and monetary impacts by NCEI area."""
    frame = result.copy()
    frame["damage_property_usd"] = frame["DAMAGE_PROPERTY"].apply(parse_damage)
    frame["damage_crops_usd"] = frame["DAMAGE_CROPS"].apply(parse_damage)
    declaration_fields = [
        column for column in DECLARATION_COLUMNS if column in frame.columns
    ]
    summary = (
        frame.groupby(
            declaration_fields
            + [
                "CZ_TYPE",
                "area_type",
                "CZ_FIPS",
                "CZ_NAME",
            ],
            dropna=False,
        )
        .agg(
            deaths_direct=("DEATHS_DIRECT", "sum"),
            injuries_direct=("INJURIES_DIRECT", "sum"),
            damage_property_usd=("damage_property_usd", "sum"),
            damage_crops_usd=("damage_crops_usd", "sum"),
            event_types=("EVENT_TYPE", lambda values: ", ".join(sorted(set(values)))),
            event_count=("EVENT_TYPE", "count"),
        )
        .reset_index()
    )
    summary["total_damage_usd"] = (
        summary["damage_property_usd"] + summary["damage_crops_usd"]
    )
    return summary.sort_values(
        ["date_signed", "declaration_id", "deaths_direct", "injuries_direct", "total_damage_usd"],
        ascending=[True, True, False, False, False],
    )


def validate_declarations(frame):
    required = {"eo_number", "event_description", "date_signed"}
    missing = sorted(required.difference(frame.columns))
    if missing:
        raise ValueError("Declaration CSV is missing: " + ", ".join(missing))


def main():
    parser = argparse.ArgumentParser(
        description="Match Virginia declarations to NCEI Storm Events"
    )
    parser.add_argument("--declarations", required=True)
    parser.add_argument("--state", default="VIRGINIA")
    parser.add_argument("--window-days", type=int, default=DEFAULT_WINDOW_DAYS)
    parser.add_argument("--out", default="eo_storm_matches.csv")
    parser.add_argument("--severity-out", default="eo_storm_severity_summary.csv")
    parser.add_argument(
        "--no-hazard-filter",
        action="store_true",
        help="match every NCEI event in the date window, including unrelated hazards",
    )
    parser.add_argument(
        "--unmatched-hazard-policy",
        choices=UNMATCHED_HAZARD_POLICIES,
        default=DEFAULT_UNMATCHED_HAZARD_POLICY,
        help=(
            "what to do when a declaration's description matches no recognized "
            "hazard keyword (default: %(default)s). 'skip' finds no NCEI matches "
            "for that declaration rather than guessing. 'all' matches every NCEI "
            "event type in its date window instead - this is the old behavior, "
            "which can silently pull in unrelated events for generically-titled "
            "declarations, so it now requires explicitly opting in. Every "
            "declaration this affects is printed as a warning either way, and "
            "listed again in the end-of-run summary."
        ),
    )
    parser.add_argument(
        "--print-all-areas",
        action="store_true",
        help="print every matched area; normally the complete list stays in the CSV",
    )
    parser.add_argument(
        "--overrides",
        default=None,
        help=(
            "path to a durable sidecar hazard-override CSV (declaration_id, "
            "hazard_category_override, plus optional review_note/source_url). "
            "Values here always win over anything already in the "
            "declarations CSV's own hazard_category_override column, and "
            "support one reserved value, 'exclude', that drops a "
            "declaration from the join entirely. See load_overrides()."
        ),
    )
    args = parser.parse_args()

    declarations = pd.read_csv(args.declarations)
    validate_declarations(declarations)
    declarations["date_signed"] = pd.to_datetime(
        declarations["date_signed"], format="%Y-%m-%d", errors="raise"
    ).dt.date
    if "declaration_id" not in declarations.columns:
        declarations["declaration_id"] = (
            declarations["eo_number"].astype(str)
            + "-"
            + declarations["date_signed"].astype(str)
        )
    for column in ["governor", "archive_record_url", "hazard_category_override"]:
        if column not in declarations.columns:
            declarations[column] = ""

    if args.overrides:
        try:
            overrides = load_overrides(args.overrides)
        except ValueError as exc:
            print(f"ERROR loading --overrides {args.overrides}: {exc}", file=sys.stderr)
            sys.exit(1)
        declarations = apply_overrides(declarations, overrides)
        print(f"Applied {len(overrides)} sidecar override(s) from {args.overrides}")

    filenames = get_latest_filenames_by_year()
    all_matches = []
    ambiguous_declarations = []
    excluded_declarations = []
    for _, declaration in declarations.iterrows():
        raw_override = declaration.get("hazard_category_override")
        if (
            raw_override is not None
            and not pd.isna(raw_override)
            and str(raw_override).strip().lower() == EXCLUDE_SENTINEL
        ):
            excluded_declarations.append(declaration["declaration_id"])
            note = declaration.get("override_review_note", "") or ""
            source = declaration.get("override_source_url", "") or ""
            detail = f" - {note}" if note else ""
            source_note = f" [source: {source}]" if source else ""
            print(
                f"EXCLUDED {declaration['declaration_id']}: reviewed as "
                f"non-weather, dropped from the join entirely{detail}{source_note}",
                file=sys.stderr,
            )
            continue
        try:
            allowed_types, ambiguous = resolve_allowed_types(
                declaration["event_description"],
                not args.no_hazard_filter,
                args.unmatched_hazard_policy,
                override=declaration.get("hazard_category_override"),
            )
        except ValueError as exc:
            print(
                f"ERROR {declaration['declaration_id']}: invalid "
                f"hazard_category_override value - {exc}. Fix this row in the "
                "declarations CSV and re-run; a malformed override is a data "
                "problem that must not be allowed to silently fall through to "
                "matching nothing or matching everything.",
                file=sys.stderr,
            )
            sys.exit(1)
        if ambiguous:
            ambiguous_declarations.append(declaration["declaration_id"])
            if allowed_types is None:
                print(
                    f"WARNING {declaration['declaration_id']}: no recognized hazard "
                    f"keyword in \"{declaration['event_description']}\" - skipped, "
                    "no NCEI search attempted. Pass --unmatched-hazard-policy all "
                    "to search every event type instead.",
                    file=sys.stderr,
                )
            else:
                print(
                    f"WARNING {declaration['declaration_id']}: no recognized hazard "
                    f"keyword in \"{declaration['event_description']}\" - matching "
                    "every NCEI event type in the date window because "
                    "--unmatched-hazard-policy all was passed.",
                    file=sys.stderr,
                )

        matches = events_near_date(
            args.state,
            declaration["date_signed"],
            args.window_days,
            filenames,
            allowed_types,
        )
        if matches.empty:
            if not (ambiguous and allowed_types is None):
                # A genuine "skip" (ambiguous, allowed_types is None) already
                # printed its own WARNING line above; no need to also claim
                # NCEI was searched and came up empty, since it wasn't.
                print(
                    f"{declaration['declaration_id']}: no matching storm events found "
                    "in the date window."
                )
            continue

        matches = matches.copy()
        for column in DECLARATION_COLUMNS:
            matches[column] = declaration[column]
        matches["area_type"] = matches["CZ_TYPE"].map(AREA_TYPE_LABELS).fillna(
            "unknown NCEI area type"
        )
        all_matches.append(matches.reindex(columns=DECLARATION_COLUMNS + EVENT_COLUMNS))

    if excluded_declarations:
        print(
            f"\n{len(excluded_declarations)} declaration(s) were excluded entirely "
            "via a reviewed override (non-weather, dropped before matching): "
            + ", ".join(str(d) for d in excluded_declarations)
        )

    if ambiguous_declarations:
        policy_note = (
            "matched against every NCEI event type in their date window"
            if args.unmatched_hazard_policy == "all"
            else "skipped (no NCEI search attempted)"
        )
        print(
            f"\n{len(ambiguous_declarations)} declaration(s) had no recognized hazard "
            f"keyword in their description and were {policy_note}: "
            + ", ".join(str(d) for d in ambiguous_declarations)
        )
        if args.unmatched_hazard_policy != "all":
            print(
                "Re-run with --unmatched-hazard-policy all if these should instead "
                "be matched against every event type - but check their real titles "
                "first; that setting is what previously let unrelated NCEI events "
                "flood the severity summary for generically-titled declarations."
            )

    if not all_matches:
        # A production rebuild must not silently retain a stale matches/
        # severity CSV from a previous run just because this run found
        # nothing - an empty result is still a result, and it must overwrite
        # whatever is on disk from before.
        empty_matches = pd.DataFrame(columns=DECLARATION_COLUMNS + EVENT_COLUMNS)
        empty_matches.to_csv(args.out, index=False)
        empty_severity = build_severity_summary(empty_matches)
        empty_severity.to_csv(args.severity_out, index=False)
        print(
            "No matches found for any declaration. Wrote empty "
            f"{args.out} and {args.severity_out} so no stale data from a "
            "prior run is left behind."
        )
        return

    result = pd.concat(all_matches, ignore_index=True).sort_values(
        ["date_signed", "declaration_id", "CZ_TYPE", "CZ_NAME", "BEGIN_DATE_TIME"]
    )
    result.to_csv(args.out, index=False)
    print(f"Wrote {len(result)} matched NCEI event rows to {args.out}")

    severity = build_severity_summary(result)
    severity.to_csv(args.severity_out, index=False)
    print(
        f"Wrote severity summary ({len(severity)} reported areas) "
        f"to {args.severity_out}"
    )

    notable = severity[
        (severity["deaths_direct"] > 0)
        | (severity["injuries_direct"] > 0)
        | (severity["total_damage_usd"] > 0)
    ]
    print("\nAreas with reported deaths, injuries, or damage:")
    if notable.empty:
        print("  None in the matched NCEI records.")
    else:
        notable_for_print = notable.sort_values(
            ["deaths_direct", "injuries_direct", "total_damage_usd"],
            ascending=False,
        )
        if not args.print_all_areas:
            notable_for_print = notable_for_print.head(25)
        for _, area in notable_for_print.iterrows():
            print(
                f"  {area['declaration_id']} {area['CZ_NAME']} "
                f"[{area['area_type']}]: deaths={int(area['deaths_direct'])}, "
                f"injuries={int(area['injuries_direct'])}, "
                f"damage=${area['total_damage_usd']:,.0f} "
                f"({area['event_types']})"
            )
        if not args.print_all_areas and len(notable) > len(notable_for_print):
            print(
                f"  Showing the 25 highest-consequence areas; all {len(notable)} "
                f"are retained in {args.severity_out}."
            )

    if args.print_all_areas:
        print("\nNCEI-reported areas per declaration:")
        for (declaration_id, eo_number, governor, description), group in result.groupby(
            ["declaration_id", "eo_number", "governor", "event_description"],
            sort=False,
            dropna=False,
        ):
            governor_label = f", {governor}" if governor else ""
            print(f"  {declaration_id}: {eo_number}{governor_label} ({description})")
            for area_type, area_group in group.groupby("area_type", sort=False):
                areas = sorted(set(area_group["CZ_NAME"].dropna()))
                print(f"    {area_type}: {', '.join(areas)}")
    else:
        print(f"\nComplete matched-area lists are in {args.severity_out}.")


if __name__ == "__main__":
    main()
